import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-laboratory-test-reimbursement-recovery",
  "engine": "recovery",
  "title": "Laboratory Test Reimbursement Recovery",
  "shortTitle": "Laboratory Test Reimbursement Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through laboratory test reimbursement recovery",
  "industry": "Laboratory Revenue Integrity",
  "uiPort": 4601,
  "apiPort": 5601,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Laboratory Test Reimbursement Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "paidAmount",
    "expectedKey": "expectedAmount",
    "actualLabel": "Payer Paid Amount",
    "expectedLabel": "Supported Test Reimbursement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Laboratory Test Reimbursement Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("test-and-panel-catalog","LTR01","Test and panel catalog","Execute test and panel catalog using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed test and panel catalog decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Test and panel catalog Reference","text","LTR01-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("order-specimen-ingestion","LTR02","Order specimen ingestion","Execute order specimen ingestion using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed order specimen ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Order specimen ingestion Reference","text","LTR02-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("medical-necessity-validation","LTR03","Medical necessity validation","Execute medical necessity validation using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed medical necessity validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Medical necessity validation Reference","text","LTR03-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("diagnosis-coverage-rules","LTR04","Diagnosis coverage rules","Execute diagnosis coverage rules using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed diagnosis coverage rules decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Diagnosis coverage rules Reference","text","LTR04-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("abn-evidence-management","LTR05","ABN evidence management","Execute abn evidence management using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed abn evidence management decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","ABN evidence management Reference","text","LTR05-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("panel-bundling-validation","LTR06","Panel bundling validation","Execute panel bundling validation using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed panel bundling validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Panel bundling validation Reference","text","LTR06-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("cpt-modifier-control","LTR07","CPT modifier control","Execute cpt modifier control using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed cpt modifier control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","CPT modifier control Reference","text","LTR07-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("reference-lab-invoice-matching","LTR08","Reference-lab invoice matching","Execute reference-lab invoice matching using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed reference-lab invoice matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Reference-lab invoice matching Reference","text","LTR08-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("payer-fee-schedule-calculation","LTR09","Payer fee schedule calculation","Execute payer fee schedule calculation using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed payer fee schedule calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Payer fee schedule calculation Reference","text","LTR09-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("claim-submission","LTR10","Claim submission","Execute claim submission using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed claim submission decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Claim submission Reference","text","LTR10-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("denial-classification","LTR11","Denial classification","Execute denial classification using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed denial classification decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Denial classification Reference","text","LTR11-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("appeal-generation","LTR12","Appeal generation","Execute appeal generation using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed appeal generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Appeal generation Reference","text","LTR12-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("remittance-reconciliation","LTR13","Remittance reconciliation","Execute remittance reconciliation using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed remittance reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Remittance reconciliation Reference","text","LTR13-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("client-versus-payer-billing","LTR14","Client versus payer billing","Execute client versus payer billing using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed client versus payer billing decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Client versus payer billing Reference","text","LTR14-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]}),
feature("test-payer-and-provider-analytics","LTR15","Test payer and provider analytics","Execute test payer and provider analytics using test catalogs, orders, specimens, diagnoses, medical necessity, ABNs, panels, CPT codes, modifiers, reference-lab invoices, claims, EOBs, and remittances.","Produce a governed test payer and provider analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Laboratory / Test Claim","text","Laboratory / Test Claim · Standard Case"],["caseReference","Test payer and provider analytics Reference","text","LTR15-2026-001"],["paidAmount","Payer Paid Amount","currency",605000],["expectedAmount","Supported Test Reimbursement","currency",713900],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"paidAmount",subjects:["Test and panel catalog case","Order specimen ingestion case","Medical necessity validation case","Diagnosis coverage rules case","ABN evidence management case"]})
]);
